version: "3.5"
services:
  rtsp-server:
    image: aler9/rtsp-simple-server
    restart: always
    ports:
      - "1935:1935"
      - "8554:8554"
      - "8888:8888"
    environment:
      - RTSP_PROTOCOLS=tcp
    networks:
      - streaming-network

  videos-streaming-worker:
    image: jrottenberg/ffmpeg
    restart: always
    links:
      - "rtsp-server:rtsp-server"
    depends_on:
      - rtsp-server
    volumes:
      - ./videos:/videos
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh","/entrypoint.sh"]
    networks:
      - streaming-network
    environment:
      - HOST_NAME=192.168.4.133

#--------------------------------------------------------------------------------
# Network
#--------------------------------------------------------------------------------

networks:
  streaming-network:
    name: streaming-environment-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1